"""TTS delivery styles for Overview voice tests and event alerts."""

from __future__ import annotations

import random
from typing import Any

DELIVERY_MODES: tuple[str, ...] = ("normal", "conspiracy", "panicky", "neurotic", "playful")

_DELIVERY_MODE_LABELS = {
    "normal": "Normal",
    "conspiracy": "Conspiracy",
    "panicky": "Panicky",
    "neurotic": "Neurotic",
    "playful": "Playful",
}

# Alex Jones–style follow-ups appended after the base detection text.
# Short punchy lines, brief one-liners, and single-word outbursts — kept TTS-friendly.
CONSPIRACY_PHRASES: tuple[str, ...] = (
    "Is he working for the globalists?",
    "Wake up.",
    "False flag?",
    "Connect the dots.",
    "Coincidence? I think not.",
    "Follow the money.",
    "They don't want you to know.",
    "The deep state knows.",
    "Info Wars was right.",
    "Classic playbook.",
    "I'm just asking questions.",
    "Who benefits?",
    "The great reset continues.",
    "Prison planet.",
    "Order out of chaos.",
    "Big Pharma hates this.",
    "Globalist puppets.",
    "Bilderberg approved.",
    "Fluoride mind control.",
    "Chemtrail fallout.",
    "Predictive programming.",
    "Media blackout incoming.",
    "They're watching you.",
    "Resistance is mandatory.",
    "The frogs warned us.",
    "It's all connected.",
    "The matrix has you.",
    "Technocracy rising.",
    "Digital gulag alert.",
    "Script flipped.",
    "Narrative collapse.",
    "They fear an awake population.",
    "The algorithm sent them.",
    "Social credit pilot.",
    "Smart city trap sprung.",
    "CBDC surveillance test.",
    "Geoengineering fallout.",
    "5G activation sequence.",
    "Red pill moment.",
    "They hate that you noticed.",
    "Quiet part said loud.",
    "Too convenient to ignore.",
    "Timing is everything.",
    "Legacy media silent again.",
    "Fact checkers hate this.",
    "Stay vigilant, stay free.",
    "The mainstream media will not report this.",
    "Is this part of the great reset agenda?",
    "The deep state is making its move.",
    "They're coming for your guns next.",
    "This is what they don't want you to know.",
    "Info Wars. The truth is under attack.",
    "Are the globalist puppet masters behind this?",
    "They turned the frogs gay, and now this?",
    "This surveillance grid is training you to obey.",
    "The Bilderberg Group planned this years ago.",
    "Interdimensional chaos agents? I'm just asking questions.",
    "The fluoride in the water made this happen.",
    "UN Agenda twenty thirty is in full swing.",
    "The synthetic teleprompter readers hate this footage.",
    "Operation Mockingbird never ended.",
    "World Economic Forum approved.",
    "Klaus Schwab smiles somewhere.",
    "Fifteen minute cities next.",
    "Eat the bugs? Never.",
    "Own nothing and be happy? No.",
    "Neural link beta test.",
    "Bohemian Grove rehearsal.",
    "Skull and Bones nod.",
    "Central bank puppet show.",
    "Hegelian dialectic in motion.",
    "Problem, reaction, solution.",
    "Manufactured consent.",
    "Gladio style ops.",
    "Black budget assets.",
    "Crisis capitalism at work.",
    "Fear porn delivered hot.",
    "Divide and conquer works.",
    "The panopticon blinks.",
    "Eyes up, sheep down.",
    "Smoking gun adjacent.",
    "Follow the patents.",
    "Defense contractor dividend.",
    "NGO money trail.",
    "Think tank script.",
    "Shadow banned in real life.",
    "Stack silver, reject fear.",
    "Patriot radio was right.",
    "Crisis actors? Maybe.",
    "Luciferian ritual timing.",
    "Bread and circuses failed.",
    "The quiet war continues.",
    "They bank on your apathy.",
    "Your camera is their weapon.",
    "Compliance is not patriotism.",
    "Question everything on TV.",
    "The scriptwriters are nervous.",
    "Another dot on the board.",
    "This is the distraction.",
    "Look what they're hiding now.",
    # Single-word outbursts
    "Unbelievable!",
    "Pathetic!",
    "Outrageous!",
    "Disgusting!",
    "Sickening!",
    "Infuriating!",
    "Treasonous!",
    "Shameful!",
    "Criminal!",
    "Corrupt!",
    "Insane!",
    "Ridiculous!",
    "Horrifying!",
    "Terrifying!",
    "Appalling!",
    "Despicable!",
    "Unacceptable!",
    "Scandalous!",
    "Revolting!",
    "Monstrous!",
    "Diabolical!",
    "Evil!",
    "Fraudulent!",
    "Compromised!",
    "Scripted!",
)

# Anxious follow-ups appended after the base detection text.
NEUROTIC_PHRASES: tuple[str, ...] = (
    "Oh dear!",
    "Lookout!",
    "I don't like the looks of this!",
    "Something's not right here.",
    "This makes me nervous.",
    "I'm getting a bad feeling.",
    "Should we be worried?",
    "That doesn't look good.",
    "Oh no, oh no.",
    "My stomach just dropped.",
    "This is giving me anxiety.",
    "I have a bad feeling about this.",
    "Please tell me I'm imagining things.",
    "That's unsettling.",
    "I'm not comfortable with this.",
    "What was that?",
    "Did you see that too?",
    "This can't be good.",
    "I'm freaking out a little.",
    "My heart is racing.",
    "That's really concerning.",
    "I need to sit down.",
    "Don't panic — I'm panicking.",
    "Why is this happening?",
    "I knew something felt off.",
    "Yikes!",
    "Uh-oh.",
    "Here we go again.",
    "Not again!",
    "I'm spiraling.",
    "Deep breaths. Deep breaths.",
    "That's a no from me.",
    "I'm officially worried.",
    "This feels wrong.",
    "My anxiety says run.",
    "I don't feel safe.",
    "That's not normal.",
    "Who authorized this?",
    "Call me paranoid, but still.",
    "I'm not okay with this.",
    "Red flag!",
    "Major red flag!",
    "My worry meter just spiked.",
    "Cue the nervous sweats.",
    "I need a minute.",
    "I'm clutching my pearls.",
    "Well, that's alarming.",
    "That's a hard pass.",
    "I'm side-eyeing this hard.",
    "My cortisol just jumped.",
    "This is too much.",
    "I'm overthinking this already.",
    "Bad vibes only.",
    "I'm hearing doom music.",
    "This ruined my whole mood.",
    "I'm pacing now.",
    "Lock the doors!",
    "Check the backyard!",
    "Is everyone accounted for?",
    "Where's the dog?",
    "Did we leave a window open?",
    "This timing is suspicious.",
    "That's awfully convenient.",
    "I'm not buying it.",
    "I'm on high alert now.",
    "Stay frosty.",
    "Eyes everywhere.",
    "Don't look away.",
    "I'm watching the replay.",
    "This needs a second look.",
    "I'm screenshotting this.",
    "Who do we call first?",
    "Should I hide?",
    "I'm definitely not going outside.",
    "My peace is gone.",
    "There goes my calm evening.",
    "I felt that in my chest.",
    "That gave me chills.",
    "I'm going to need tea after this.",
    "Say it ain't so.",
    "Please be a false alarm.",
    "I'm begging this to be nothing.",
    "My therapist warned me about days like this.",
    "I knew I shouldn't have checked the cameras.",
    "Why did I look?",
    "Curiosity is a curse.",
    "I'm regretting everything.",
    "This is my villain origin story.",
    "I'm too delicate for this.",
    "My nervous system cannot.",
    "I don't know what it is, but something about this whole situation is making my skin crawl.",
    "Can we please double-check the locks? I'm not going to be able to sleep after seeing this.",
    "I've been saying all week that something felt wrong, and now here's proof on camera.",
    "This is exactly the kind of thing I warned everyone about, and nobody listened to me.",
    "My hands are literally shaking — I hope you're taking this as seriously as I am.",
    "I keep telling myself it's probably nothing, but my gut has never been wrong about this stuff.",
    "We need to call someone. I don't care who — just please don't tell me to calm down.",
    "I was already on edge today and this is absolutely the last thing I needed to see.",
    "Something tells me we're not getting the full picture here, and that scares me even more.",
    "I've replayed this in my head six different ways and none of them end well.",
    "I wonder what this means for me?",
    "How does this impact me?",
    "Is this going to affect my day?",
    "What am I supposed to do with this information?",
    "Why do I feel personally targeted by this?",
    "Does this change anything for us?",
    "I'm already catastrophizing and we just started.",
    "What if this is somehow about me?",
    "I need to know how worried I should be.",
    "Is my routine ruined now?",
    "This feels like it has implications for me.",
    "I'm taking this personally and I know that's a problem.",
    "What does this mean for my peace of mind?",
    "How am I expected to unsee this?",
    "I don't love what this suggests about my evening.",
    "Is this the kind of thing that follows you?",
    "I'm mentally drafting worst-case scenarios already.",
    "What if this escalates and I'm not ready?",
    "Does anyone else feel personally inconvenienced by this?",
    "I need a moment to process what this means for me.",
    "How long am I going to think about this?",
    "This has personal stakes and I hate that.",
    "I'm worried about the downstream effects on my nerves.",
    "What am I supposed to tell myself after seeing this?",
    "Is this going to be the thing I obsess over tonight?",
)

# Flirty follow-ups appended after the base detection text.
PLAYFUL_PHRASES: tuple[str, ...] = (
    "Oh my!",
    "Wow, that looks good.",
    "Yummy!",
    "Hello there.",
    "Well, hello handsome.",
    "My, my, my.",
    "Be still my heart.",
    "Ooh la la!",
    "Hubba hubba.",
    "Looking sharp out there.",
    "Don't mind me staring.",
    "That's a nice view.",
    "Come here often?",
    "Caught my eye.",
    "Check you out.",
    "Yes please.",
    "Dreamy.",
    "You're making me blush.",
    "Come on over.",
    "Miss me yet?",
    "Nice move.",
    "That's the one.",
    "Well aren't you something.",
    "Looking good, sweetheart.",
    "Stop being so cute.",
    "Well hello, stranger.",
    "Aren't you a sight.",
    "My heart just skipped.",
    "That's what I like to see.",
    "Come to mama.",
    "Looking delicious.",
    "Oh you tease.",
    "My oh my.",
    "Sweet thing.",
    "Hello gorgeous.",
    "That's tempting.",
    "Come closer.",
    "You're a keeper.",
    "What a catch.",
    "I'm impressed.",
    "Very nice indeed.",
    "That's the good stuff.",
    "Hello, beautiful.",
    "Well well well.",
    "Look who's here.",
    "Fancy meeting you.",
    "You're trouble.",
    "I see you.",
    "Can't look away.",
    "That's hot.",
    "Hello, sunshine.",
    "You're a whole mood.",
    "Making hearts race.",
    "Too cute to handle.",
    "I'm not complaining.",
    "That's a ten.",
    "Chef's kiss.",
    "Perfection.",
    "Absolutely stunning.",
    "You're killing me.",
    "Sweet as pie.",
    "Butterflies activated.",
    "My type right there.",
    "That's the vibe.",
    "Hello, dreamboat.",
    "Looking fine today.",
    "You clean up nice.",
    "That's irresistible.",
    "Come say hi.",
    "Worth the wait.",
    "Hello, cutie pie.",
    "You're a whole snack.",
    "That's the highlight.",
    "Making it interesting.",
    "Oh, behave.",
    "You're too much.",
    "I'm swooning.",
    "That's adorable.",
    "Hello, heartbreaker.",
    "Looking like trouble.",
    "You got my attention.",
    "That's a winner.",
    "You're on fire.",
    "That's the energy.",
    "Come through.",
    "Looking extra today.",
    "You're a gem.",
    "Hello, good lookin.",
    "You're a vision.",
    "Making me smile.",
    "Oh, you're good.",
    "Hello, charmer.",
    "You're a delight.",
    "Looking like a star.",
    "You're a knockout.",
    "Making my day.",
    "Oh, I like that.",
    "Hello, darling.",
    "You're a flame.",
    "Making hearts flutter.",
)


def normalize_delivery_mode(value: Any) -> str:
    mode = str(value or "normal").strip().lower()
    return mode if mode in DELIVERY_MODES else "normal"


def delivery_mode_label(mode: str) -> str:
    return _DELIVERY_MODE_LABELS.get(normalize_delivery_mode(mode), "Normal")


def pick_conspiracy_phrase() -> str:
    """Pick a random phrase from the conspiracy pool."""
    return random.choice(CONSPIRACY_PHRASES)


def pick_neurotic_phrase() -> str:
    """Pick a random phrase from the neurotic pool."""
    return random.choice(NEUROTIC_PHRASES)


def pick_playful_phrase() -> str:
    """Pick a random phrase from the playful pool."""
    return random.choice(PLAYFUL_PHRASES)


def apply_delivery_mode(text: str, mode: str) -> str:
    """Rewrite alert text for conspiracy, panicky, neurotic, or playful delivery styles."""
    base = (text or "").strip()
    if not base:
        return base
    delivery = normalize_delivery_mode(mode)
    if delivery == "conspiracy":
        return f"{base}. {pick_conspiracy_phrase()}"
    if delivery == "neurotic":
        return f"{base}. {pick_neurotic_phrase()}"
    if delivery == "playful":
        return f"{base}. {pick_playful_phrase()}"
    if delivery == "panicky":
        return (
            f"Alert! Alert! {base}! "
            "This is not a drill! Somebody check the cameras now!"
        )
    return base